# Generated by Django 5.1.5 on 2025-02-09 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('developer', 'Developer'), ('designer', 'Designer'), ('manager', 'Manager')], default='developer', max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('github', models.URLField(blank=True, null=True)),
                ('objective', models.TextField()),
                ('address', models.TextField()),
                ('total_experience', models.FloatField(help_text='Total experience in years')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
            ],
        ),
    ]
